"""empty message

Revision ID: 24c9a0eca8c8
Revises: e3c5ae1e96de
Create Date: 2024-01-19 23:26:18.866848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c9a0eca8c8'
down_revision = 'e3c5ae1e96de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(length=580), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
