"""empty message

Revision ID: 540f4182defc
Revises: e30967d1c294
Create Date: 2024-01-14 15:45:11.606647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540f4182defc'
down_revision = 'e30967d1c294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=580), nullable=False))
        batch_op.drop_column('salt')
        batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.VARCHAR(length=580), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(length=580), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
